//! Core code generation: Lexicon types -> Rust source.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use proto_blue_lexicon::types::{
    LexObject, LexRefUnion, LexUserType, LexXrpcError, LexXrpcParameters, LexXrpcProcedure,
    LexXrpcQuery, LexXrpcSubscription, LexiconDoc,
};

/// Code generator that converts Lexicon documents to Rust source files.
pub struct Generator<'a> {
    docs: &'a [LexiconDoc],
}

impl<'a> Generator<'a> {
    pub const fn new(docs: &'a [LexiconDoc]) -> Self {
        Generator { docs }
    }

    /// Generate all Rust source files. Returns a map of relative path -> content.
    pub fn generate(&self) -> BTreeMap<String, String> {
        let mut files = BTreeMap::new();

        // Track module tree for mod.rs generation
        // Key: directory path, Value: set of child module names
        let mut mod_tree: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();

        // PASS 1 — build the full mod_tree first so PASS 2 can decide
        // per-doc whether an NSID is both a leaf AND a parent. The
        // leaf-and-parent case occurs in the wild (e.g. third-party
        // lexicons that publish `com.example.foo` AND
        // `com.example.foo.bar`) and was the cause of #23 (E0761:
        // ambiguous module file at `<name>.rs` + `<name>/mod.rs`).
        for doc in self.docs {
            let nsid = &doc.id;
            let parts: Vec<&str> = nsid.split('.').collect();
            if parts.len() < 2 {
                continue;
            }
            for i in 0..parts.len() {
                let dir = if i == 0 {
                    String::new()
                } else {
                    parts[..i].join("/")
                };
                let child = parts[i];
                mod_tree.entry(dir).or_default().insert(child.to_string());
            }
        }

        // PASS 2 — emit each lexicon's generated file. When the NSID is
        // ALSO a parent in `mod_tree` (has child NSIDs), write to
        // `<path>/mod.rs` instead of `<path>.rs`; PASS 3 will append the
        // mod-tree directives for the children to the same file.
        for doc in self.docs {
            let nsid = &doc.id;
            let parts: Vec<&str> = nsid.split('.').collect();
            if parts.len() < 2 {
                continue;
            }
            let dir_path = parts.join("/");
            let is_branch = mod_tree.contains_key(&dir_path);
            let file_path = if is_branch {
                format!("{dir_path}/mod.rs")
            } else {
                format!("{dir_path}.rs")
            };
            let content = Self::generate_file(doc);
            files.insert(file_path, content);
        }

        // PASS 3 — emit a `mod.rs` per directory in `mod_tree`, declaring
        // each child module. If a leaf-and-parent already wrote content
        // to `<dir>/mod.rs` in PASS 2 we APPEND the directives below it
        // rather than overwrite (the leaf's defs and the children's
        // sub-modules coexist in one `mod.rs`).
        //
        // Leaf children whose NSID segment differs from its snake-case
        // form (e.g. `getSession`) get a `#[path = "<orig>.rs"]` attribute
        // so the on-disk filename stays NSID-canonical while the Rust
        // module name is clean. Same applies to non-leaf segments
        // containing dashes (e.g. `bad-example`) — see #24, where the
        // missing path attribute on dirs caused E0583.
        for (dir, children) in &mod_tree {
            let mod_path = if dir.is_empty() {
                "mod.rs".to_string()
            } else {
                format!("{dir}/mod.rs")
            };
            let existing = files.get(&mod_path).cloned();
            let mut mod_content = String::new();
            if existing.is_none() {
                mod_content.push_str("// Generated by atproto-codegen. Do not edit.\n");
                // Pedantic+nursery lints are advisory for codegen output —
                // the generator can't audit every cast/doc/struct it emits.
                // Hand-written sites keep the default lint floor; suppress
                // only what would otherwise drown out real signal.
                mod_content
                    .push_str("#![allow(clippy::pedantic, clippy::nursery, clippy::all)]\n\n");
            }

            let mut child_list: Vec<&String> = children.iter().collect();
            child_list.sort();

            for child in child_list {
                let is_leaf = !mod_tree.contains_key(&join_dir(dir, child));
                let snake = to_snake_case(child);
                let rust_ident = sanitize_ident(&snake);
                let needs_path_attr = snake != *child;
                if needs_path_attr {
                    // Disk path uses the original NSID segment; Rust
                    // module name uses the snake form. The suffix
                    // distinguishes leaf .rs from branch /mod.rs.
                    let suffix = if is_leaf { ".rs" } else { "/mod.rs" };
                    writeln!(
                        mod_content,
                        "#[path = \"{child}{suffix}\"]\npub mod {rust_ident};"
                    )
                    .expect("infallible write to String");
                } else {
                    writeln!(mod_content, "pub mod {rust_ident};")
                        .expect("infallible write to String");
                }
            }

            // Append below the leaf's content, or take over a fresh mod.rs.
            if let Some(existing_content) = existing {
                files.insert(mod_path, format!("{existing_content}\n{mod_content}"));
            } else {
                files.insert(mod_path, mod_content);
            }
        }

        files
    }

    /// Generate a single Rust source file for a lexicon document.
    ///
    /// The serde import is emitted conditionally: lexicon documents
    /// that only produce free functions (e.g. `call()` wrappers
    /// without an `Output` struct) don't derive `Deserialize` /
    /// `Serialize` and would leave the `use` dangling as a warning.
    fn generate_file(doc: &LexiconDoc) -> String {
        let nsid = &doc.id;

        // Render defs into a scratch buffer first so we can decide
        // whether the serde import is needed based on the real output.
        let mut body = String::new();
        let mut def_names: Vec<&String> = doc.defs.keys().collect();
        def_names.sort();
        for def_name in def_names {
            let def = &doc.defs[def_name];
            Self::generate_def(&mut body, nsid, def_name, def);
        }

        let mut out = String::new();
        out.push_str("// Generated by atproto-codegen. Do not edit.\n");
        writeln!(out, "//! Lexicon: {nsid}").expect("infallible write to String");
        // Pedantic+nursery lints are advisory for codegen output — the
        // generator can't audit every cast/doc/struct it emits. Hand-
        // written sites keep the default lint floor; suppress only what
        // would otherwise drown out real signal in pedantic sweeps.
        out.push_str("#![allow(clippy::pedantic, clippy::nursery, clippy::all)]\n\n");
        if body.contains("Deserialize") || body.contains("Serialize") {
            out.push_str("use serde::{Deserialize, Serialize};\n\n");
        }
        out.push_str(&body);

        out
    }

    /// Generate Rust code for a single definition.
    fn generate_def(out: &mut String, nsid: &str, def_name: &str, def: &LexUserType) {
        let type_name = def_name_to_type(def_name);

        match def {
            LexUserType::Record(rec) => {
                Self::generate_object(out, nsid, &type_name, &rec.record, true);
            }
            LexUserType::Object(obj) => {
                Self::generate_object(out, nsid, &type_name, obj, false);
            }
            LexUserType::Query(query) => {
                Self::generate_query(out, nsid, &type_name, query);
            }
            LexUserType::Procedure(proc) => {
                Self::generate_procedure(out, nsid, &type_name, proc);
            }
            LexUserType::Subscription(sub) => {
                Self::generate_subscription(out, nsid, &type_name, sub);
            }
            LexUserType::Array(arr) => {
                // Top-level array definitions get a type alias
                let inner = Self::type_to_rust(nsid, &arr.items);
                if let Some(desc) = &arr.description {
                    writeln!(out, "/// {}", escape_doc_text(desc))
                        .expect("infallible write to String");
                }
                writeln!(out, "pub type {type_name} = Vec<{inner}>;")
                    .expect("infallible write to String");
                out.push('\n');
            }
            LexUserType::String(s) => {
                if let Some(enum_values) = &s.enum_values {
                    Self::generate_string_enum(
                        out,
                        &type_name,
                        enum_values,
                        s.description.as_deref(),
                    );
                } else if let Some(known_values) = &s.known_values {
                    Self::generate_known_values(
                        out,
                        &type_name,
                        known_values,
                        s.description.as_deref(),
                    );
                }
                // Plain strings don't need a type alias
            }
            LexUserType::Token(t) => {
                if let Some(desc) = &t.description {
                    writeln!(out, "/// {}", escape_doc_text(desc))
                        .expect("infallible write to String");
                }
                writeln!(
                    out,
                    "pub const {}: &str = \"{nsid}#{def_name}\";",
                    to_screaming_snake(&type_name)
                )
                .expect("infallible write to String");
                out.push('\n');
            }
            LexUserType::Union(union_def) => {
                Self::generate_union(out, nsid, &type_name, union_def);
            }
            // Other types don't generate standalone definitions
            _ => {}
        }
    }

    /// Generate a Rust struct for a Lexicon object.
    fn generate_object(
        out: &mut String,
        nsid: &str,
        type_name: &str,
        obj: &LexObject,
        is_record: bool,
    ) {
        // Aux-type buffer for synthesised inline unions. Inline unions
        // appear as struct properties whose type is `LexUserType::Union`
        // (or arrays thereof); they need a named sibling enum so the
        // struct field's type isn't a bare `serde_json::Value`. We
        // collect those defs here and emit them BEFORE the struct so
        // the struct can reference them by name.
        let mut aux_types = String::new();
        let mut struct_body = String::new();

        // Sort properties for deterministic output
        let mut prop_names: Vec<&String> = obj.properties.keys().collect();
        prop_names.sort();

        let required: BTreeSet<&str> = obj.required.iter().map(String::as_str).collect();
        let nullable: BTreeSet<&str> = obj.nullable.iter().map(String::as_str).collect();
        let mut seen_idents: std::collections::HashSet<String> = std::collections::HashSet::new();
        // Pre-seed with the synthetic `r#type` field that records emit so
        // a real lexicon `type` property doesn't collide with it.
        if is_record {
            seen_idents.insert("r#type".to_string());
        }

        for prop_name in prop_names {
            let prop_type = &obj.properties[prop_name];
            let is_required = required.contains(prop_name.as_str());
            let is_nullable = nullable.contains(prop_name.as_str());

            let raw_rust_name = to_snake_case(prop_name);
            let rust_name = disambiguate(&mut seen_idents, raw_rust_name.clone());
            let was_disambiguated = rust_name != raw_rust_name;

            // Compose a base name hint for any inline union/array-of-union
            // the property's type contains: `<TypeName><PropertyPascalCase>`.
            // The helper appends the right discriminating suffix at the
            // union-emission site (`Refs` for Union, with `Item` inserted
            // before it for `Array<Union>`).
            let union_name_hint = format!("{type_name}{}", to_pascal_case(prop_name));
            let rust_type =
                Self::type_to_rust_with_unions(nsid, prop_type, &mut aux_types, &union_name_hint);

            // Doc-comment the disambiguation so a reader of the generated
            // file can see why the Rust name doesn't match the wire name.
            if was_disambiguated {
                writeln!(
                    struct_body,
                    "    /// Renamed from `{prop_name}` to avoid a Rust identifier collision with a sibling field."
                )
                .expect("infallible write to String");
            }

            // Add serde rename if snake_case differs from camelCase, or if
            // disambiguation produced a name that won't round-trip.
            let needs_rename = rust_name != *prop_name && to_camel_case(&rust_name) != *prop_name;
            if needs_rename {
                writeln!(struct_body, "    #[serde(rename = \"{prop_name}\")]")
                    .expect("infallible write to String");
            }

            if is_required {
                if is_nullable {
                    writeln!(struct_body, "    pub {rust_name}: Option<{rust_type}>,")
                        .expect("infallible write to String");
                } else {
                    writeln!(struct_body, "    pub {rust_name}: {rust_type},")
                        .expect("infallible write to String");
                }
            } else {
                struct_body.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
                writeln!(struct_body, "    pub {rust_name}: Option<{rust_type}>,")
                    .expect("infallible write to String");
            }
        }

        // Now emit everything in order: aux types (synthesised unions),
        // then the struct's doc comment + TYPE const + struct itself.
        out.push_str(&aux_types);

        if let Some(desc) = &obj.description
            && !desc.is_empty()
        {
            writeln!(out, "/// {}", escape_doc_text(desc)).expect("infallible write to String");
        }
        // Records carry a `$type` field on the wire — emit a TYPE
        // constant and a serde-serialised `type` field so round-trips
        // preserve the discriminator. Matches TS AtpAgent / codegen.
        if is_record {
            writeln!(
                out,
                "/// `$type` discriminator for this record on the wire.\n\
                 pub const TYPE: &str = \"{nsid}\";"
            )
            .expect("infallible write to String");
            out.push('\n');
        }
        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        out.push_str("#[serde(rename_all = \"camelCase\")]\n");
        writeln!(out, "pub struct {type_name} {{").expect("infallible write to String");

        if is_record {
            // Serialised as "$type": "<nsid>"; deserialisation preserves
            // whatever was on the wire (including absent, in which case
            // the default is the canonical type string for this NSID).
            out.push_str(
                "    /// The `$type` discriminator. Defaults to [`TYPE`] on construction.\n",
            );
            out.push_str("    #[serde(rename = \"$type\", default = \"default_type\")]\n");
            out.push_str("    pub r#type: String,\n");
        }

        out.push_str(&struct_body);
        out.push_str("}\n\n");

        // Emit the serde `default = "default_type"` helper that the
        // `$type` field uses, so users can deserialise records that
        // omit `$type` without a custom impl.
        if is_record {
            out.push_str("fn default_type() -> String {\n");
            out.push_str("    TYPE.to_string()\n");
            out.push_str("}\n\n");
        }
    }

    /// Variant of `type_to_rust` that materialises inline-union types
    /// instead of falling back to `serde_json::Value`.
    ///
    /// When the type contains a `LexUserType::Union` (directly or nested
    /// inside an `Array`), emits a synthesised sum-type enum into
    /// `aux_out` and returns the synthesised name in place of
    /// `serde_json::Value`. For non-union types, behaves identically to
    /// `type_to_rust`.
    ///
    /// Naming: the caller passes a base `name_hint` unique per
    /// (struct, property) pair (typically `<StructName><PropertyPascalCase>`,
    /// e.g. `MainEmbed`). The helper composes:
    ///   - direct `Union`              → `<name_hint>Refs`         (e.g. `MainEmbedRefs`)
    ///   - `Array<Union>`              → `<name_hint>ItemRefs`     (e.g. `MainFacetsItemRefs`)
    ///   - `Array<Array<Union>>`       → `<name_hint>ItemItemRefs`
    ///
    /// The trailing `Refs` matches the lexicon term (`refs: [...]`) and
    /// guarantees the synthesised name doesn't collide with same-named
    /// top-level defs in the same module — e.g. `app.bsky.embed.record`
    /// defines a `viewRecord` struct (→ `ViewRecord`) and a `view` struct
    /// whose `record` property is a union; without the suffix the
    /// synthesised union would also be `ViewRecord`.
    fn type_to_rust_with_unions(
        nsid: &str,
        ty: &LexUserType,
        aux_out: &mut String,
        name_hint: &str,
    ) -> String {
        match ty {
            LexUserType::Union(union_def) => {
                let synth_name = format!("{name_hint}Refs");
                Self::generate_union(aux_out, nsid, &synth_name, union_def);
                synth_name
            }
            LexUserType::Array(arr) => {
                let inner_hint = format!("{name_hint}Item");
                let inner = Self::type_to_rust_with_unions(nsid, &arr.items, aux_out, &inner_hint);
                format!("Vec<{inner}>")
            }
            // Non-union, non-array: defer to the existing mapping.
            _ => Self::type_to_rust(nsid, ty),
        }
    }

    /// Generate a query (GET endpoint).
    fn generate_query(out: &mut String, nsid: &str, _type_name: &str, query: &LexXrpcQuery) {
        let has_params = query
            .parameters
            .as_ref()
            .is_some_and(|p| !p.properties.is_empty());
        let has_output = query.output.as_ref().is_some_and(|o| o.schema.is_some());

        // Only emit doc comment if we're generating something after it
        if has_params || has_output {
            if let Some(desc) = &query.description {
                writeln!(out, "/// {}", escape_doc_text(desc)).expect("infallible write to String");
            }
            writeln!(out, "/// XRPC Query: {nsid}").expect("infallible write to String");
        }

        if let Some(params) = &query.parameters
            && !params.properties.is_empty()
        {
            Self::generate_params(out, nsid, params);
        }

        if let Some(output) = &query.output
            && let Some(schema) = &output.schema
        {
            Self::generate_body_schema(out, nsid, "Output", schema);
        }

        Self::generate_errors(out, &query.errors);
        Self::generate_query_call_fn(out, nsid, query);
        Self::generate_query_register_fn(out, nsid, query);
    }

    /// Generate a procedure (POST endpoint).
    fn generate_procedure(out: &mut String, nsid: &str, _type_name: &str, proc: &LexXrpcProcedure) {
        let has_params = proc
            .parameters
            .as_ref()
            .is_some_and(|p| !p.properties.is_empty());
        let has_input = proc.input.as_ref().is_some_and(|i| i.schema.is_some());
        let has_output = proc.output.as_ref().is_some_and(|o| o.schema.is_some());

        if has_params || has_input || has_output {
            if let Some(desc) = &proc.description {
                writeln!(out, "/// {}", escape_doc_text(desc)).expect("infallible write to String");
            }
            writeln!(out, "/// XRPC Procedure: {nsid}").expect("infallible write to String");
        }

        if let Some(params) = &proc.parameters
            && !params.properties.is_empty()
        {
            Self::generate_params(out, nsid, params);
        }

        if let Some(input) = &proc.input
            && let Some(schema) = &input.schema
        {
            Self::generate_body_schema(out, nsid, "Input", schema);
        }

        if let Some(output) = &proc.output
            && let Some(schema) = &output.schema
        {
            Self::generate_body_schema(out, nsid, "Output", schema);
        }

        Self::generate_errors(out, &proc.errors);
        Self::generate_procedure_call_fn(out, nsid, proc);
        Self::generate_procedure_register_fn(out, nsid, proc);
    }

    /// Emit a per-method error enum from the `errors` array on the def.
    ///
    /// The enum captures each `def.errors[].name` as a variant so
    /// callers can `match` against well-known codes, with a catch-all
    /// `Xrpc(XrpcError)` for anything the lexicon doesn't enumerate
    /// plus `Fetch`/`Json` transports.
    fn generate_errors(out: &mut String, errors: &[LexXrpcError]) {
        // Always emit the error enum — even when `errors` is empty
        // we want a consistent `CallError` type per method so the
        // `call` signature is uniform.
        out.push_str("/// Errors a `call()` on this method can return.\n");
        out.push_str("#[derive(Debug, thiserror::Error)]\n");
        out.push_str("pub enum CallError {\n");
        for e in errors {
            if let Some(desc) = &e.description {
                let clean = escape_doc_text(&desc.replace('\n', " "));
                writeln!(out, "    /// {clean}").expect("infallible write to String");
            }
            let variant = to_pascal_case(&e.name);
            writeln!(out, "    #[error(\"{}\")]", e.name).expect("infallible write to String");
            writeln!(out, "    {variant},").expect("infallible write to String");
        }
        out.push_str("    #[error(\"{0}\")]\n");
        out.push_str("    Xrpc(proto_blue_xrpc::XrpcError),\n");
        out.push_str("    #[error(transparent)]\n");
        out.push_str("    Transport(#[from] proto_blue_xrpc::Error),\n");
        out.push_str("    #[error(transparent)]\n");
        out.push_str("    Json(#[from] serde_json::Error),\n");
        out.push_str("}\n\n");

        // Mapper from a raw XrpcError to the specific CallError variant
        // when the error `name` matches one of the enumerated codes;
        // otherwise wraps as `CallError::Xrpc(err)`. Emitted as a
        // single `match` on `err.error.as_deref()` to avoid clippy's
        // `single_match` warning when there's only one enumerated
        // variant.
        out.push_str("fn map_xrpc_error(err: proto_blue_xrpc::XrpcError) -> CallError {\n");
        if errors.is_empty() {
            out.push_str("    CallError::Xrpc(err)\n");
        } else {
            out.push_str("    match err.error.as_deref() {\n");
            for e in errors {
                let variant = to_pascal_case(&e.name);
                writeln!(out, "        Some(\"{}\") => CallError::{variant},", e.name)
                    .expect("infallible write to String");
            }
            out.push_str("        _ => CallError::Xrpc(err),\n");
            out.push_str("    }\n");
        }
        out.push_str("}\n\n");
    }

    /// Emit the `call()` helper for a query.
    fn generate_query_call_fn(out: &mut String, nsid: &str, query: &LexXrpcQuery) {
        let has_params = query
            .parameters
            .as_ref()
            .is_some_and(|p| !p.properties.is_empty());
        let has_output = query.output.as_ref().is_some_and(|o| o.schema.is_some());

        // Emit `to_query_params` translator when we have params.
        if has_params && let Some(params) = &query.parameters {
            Self::generate_to_query_params(out, params);
        }

        out.push_str("/// Execute the query.\n");
        out.push_str("pub async fn call(\n");
        out.push_str("    client: &proto_blue_xrpc::XrpcClient,\n");
        if has_params {
            out.push_str("    params: Option<&Params>,\n");
        }
        out.push_str("    opts: Option<&proto_blue_xrpc::CallOptions>,\n");
        if has_output {
            out.push_str(") -> Result<Output, CallError> {\n");
        } else {
            out.push_str(") -> Result<serde_json::Value, CallError> {\n");
        }
        if has_params {
            out.push_str("    let qp = params.map(to_query_params);\n");
            writeln!(
                out,
                "    let response = match client.query(\"{nsid}\", qp.as_ref(), opts).await {{"
            )
            .expect("infallible write to String");
        } else {
            writeln!(
                out,
                "    let response = match client.query(\"{nsid}\", None, opts).await {{"
            )
            .expect("infallible write to String");
        }
        out.push_str("        Ok(r) => r,\n");
        out.push_str(
            "        Err(proto_blue_xrpc::Error::Xrpc(x)) => return Err(map_xrpc_error(x)),\n",
        );
        out.push_str("        Err(e) => return Err(CallError::Transport(e)),\n");
        out.push_str("    };\n");
        if has_output {
            out.push_str("    Ok(serde_json::from_value(response.data)?)\n");
        } else {
            out.push_str("    Ok(response.data)\n");
        }
        out.push_str("}\n\n");
    }

    /// Emit the `call()` helper for a procedure.
    fn generate_procedure_call_fn(out: &mut String, nsid: &str, proc: &LexXrpcProcedure) {
        let has_params = proc
            .parameters
            .as_ref()
            .is_some_and(|p| !p.properties.is_empty());
        let has_input = proc.input.as_ref().is_some_and(|i| i.schema.is_some());
        let has_output = proc.output.as_ref().is_some_and(|o| o.schema.is_some());

        if has_params && let Some(params) = &proc.parameters {
            Self::generate_to_query_params(out, params);
        }

        out.push_str("/// Execute the procedure.\n");
        out.push_str("pub async fn call(\n");
        out.push_str("    client: &proto_blue_xrpc::XrpcClient,\n");
        if has_params {
            out.push_str("    params: Option<&Params>,\n");
        }
        if has_input {
            out.push_str("    input: &Input,\n");
        }
        out.push_str("    opts: Option<&proto_blue_xrpc::CallOptions>,\n");
        if has_output {
            out.push_str(") -> Result<Output, CallError> {\n");
        } else {
            out.push_str(") -> Result<serde_json::Value, CallError> {\n");
        }
        if has_params {
            out.push_str("    let qp = params.map(to_query_params);\n");
            out.push_str("    let qp_ref = qp.as_ref();\n");
        } else {
            out.push_str("    let qp_ref: Option<&proto_blue_xrpc::QueryParams> = None;\n");
        }
        if has_input {
            out.push_str(
                "    let body = proto_blue_xrpc::XrpcBody::Json(serde_json::to_value(input)?);\n",
            );
            writeln!(
                out,
                "    let response = match client.procedure(\"{nsid}\", qp_ref, Some(body), opts).await {{"
            )
            .expect("infallible write to String");
        } else {
            writeln!(
                out,
                "    let response = match client.procedure(\"{nsid}\", qp_ref, None, opts).await {{"
            )
            .expect("infallible write to String");
        }
        out.push_str("        Ok(r) => r,\n");
        out.push_str(
            "        Err(proto_blue_xrpc::Error::Xrpc(x)) => return Err(map_xrpc_error(x)),\n",
        );
        out.push_str("        Err(e) => return Err(CallError::Transport(e)),\n");
        out.push_str("    };\n");
        if has_output {
            out.push_str("    Ok(serde_json::from_value(response.data)?)\n");
        } else {
            out.push_str("    Ok(response.data)\n");
        }
        out.push_str("}\n\n");
    }

    /// Emit the server-side `register()` helper for a query.
    ///
    /// The handler receives typed `Params` (when declared) and
    /// returns `Result<Output, CallError>` (or `Result<JsonValue,
    /// CallError>` when the method has no output schema). The helper
    /// converts the raw `HandlerContext` into typed params and
    /// serialises the output.
    ///
    /// Gated behind the `server` feature so this module compiles
    /// client-side without pulling in axum.
    fn generate_query_register_fn(out: &mut String, nsid: &str, query: &LexXrpcQuery) {
        let has_params = query
            .parameters
            .as_ref()
            .is_some_and(|p| !p.properties.is_empty());
        let has_output = query.output.as_ref().is_some_and(|o| o.schema.is_some());
        out.push_str(
            "/// Register a typed handler for this method on an [`proto_blue_xrpc::XrpcServer`].\n",
        );
        out.push_str("#[cfg(feature = \"server\")]\n");
        out.push_str(
            "pub fn register<F, Fut>(\n\
                 server: proto_blue_xrpc::XrpcServer,\n\
                 handler: F,\n\
             ) -> proto_blue_xrpc::XrpcServer\n",
        );
        out.push_str("where\n");
        if has_params {
            out.push_str("    F: Fn(proto_blue_xrpc::HandlerContext, Option<Params>) -> Fut + Send + Sync + 'static,\n");
        } else {
            out.push_str(
                "    F: Fn(proto_blue_xrpc::HandlerContext) -> Fut + Send + Sync + 'static,\n",
            );
        }
        if has_output {
            out.push_str("    Fut: std::future::Future<Output = Result<Output, proto_blue_xrpc::XrpcServerError>> + Send + 'static,\n");
        } else {
            out.push_str("    Fut: std::future::Future<Output = Result<serde_json::Value, proto_blue_xrpc::XrpcServerError>> + Send + 'static,\n");
        }
        out.push_str("{\n");
        out.push_str("    let handler = std::sync::Arc::new(handler);\n");
        writeln!(out, "    server.query(\"{nsid}\", move |ctx| {{")
            .expect("infallible write to String");
        out.push_str("        let handler = handler.clone();\n");
        out.push_str("        async move {\n");
        if has_params {
            out.push_str("            let params = params_from_ctx(&ctx);\n");
            out.push_str("            let out = handler(ctx, params).await?;\n");
        } else {
            out.push_str("            let out = handler(ctx).await?;\n");
        }
        if has_output {
            out.push_str("            let value = serde_json::to_value(&out)\n");
            out.push_str("                .map_err(|e| proto_blue_xrpc::XrpcServerError::new(proto_blue_xrpc::ResponseType::InternalServerError, format!(\"output serialize: {e}\")))?;\n");
            out.push_str("            Ok::<_, proto_blue_xrpc::XrpcServerError>(value)\n");
        } else {
            out.push_str("            Ok::<_, proto_blue_xrpc::XrpcServerError>(out)\n");
        }
        out.push_str("        }\n");
        out.push_str("    })\n");
        out.push_str("}\n\n");
        if has_params && let Some(params) = &query.parameters {
            Self::generate_params_from_ctx(out, params);
        }
    }

    /// Emit the server-side `register()` helper for a procedure.
    fn generate_procedure_register_fn(out: &mut String, nsid: &str, proc: &LexXrpcProcedure) {
        let has_params = proc
            .parameters
            .as_ref()
            .is_some_and(|p| !p.properties.is_empty());
        let has_input = proc.input.as_ref().is_some_and(|i| i.schema.is_some());
        let has_output = proc.output.as_ref().is_some_and(|o| o.schema.is_some());
        out.push_str("/// Register a typed handler for this procedure on an [`proto_blue_xrpc::XrpcServer`].\n");
        out.push_str("#[cfg(feature = \"server\")]\n");
        out.push_str(
            "pub fn register<F, Fut>(\n\
                 server: proto_blue_xrpc::XrpcServer,\n\
                 handler: F,\n\
             ) -> proto_blue_xrpc::XrpcServer\n",
        );
        out.push_str("where\n");
        let mut arg = String::from("proto_blue_xrpc::HandlerContext");
        if has_params {
            arg.push_str(", Option<Params>");
        }
        if has_input {
            arg.push_str(", Option<Input>");
        }
        writeln!(out, "    F: Fn({arg}) -> Fut + Send + Sync + 'static,")
            .expect("infallible write to String");
        if has_output {
            out.push_str("    Fut: std::future::Future<Output = Result<Output, proto_blue_xrpc::XrpcServerError>> + Send + 'static,\n");
        } else {
            out.push_str("    Fut: std::future::Future<Output = Result<serde_json::Value, proto_blue_xrpc::XrpcServerError>> + Send + 'static,\n");
        }
        out.push_str("{\n");
        out.push_str("    let handler = std::sync::Arc::new(handler);\n");
        writeln!(out, "    server.procedure(\"{nsid}\", move |ctx| {{")
            .expect("infallible write to String");
        out.push_str("        let handler = handler.clone();\n");
        out.push_str("        async move {\n");
        if has_params {
            out.push_str("            let params = params_from_ctx(&ctx);\n");
        }
        if has_input {
            out.push_str("            let input = match ctx.json_body()? {\n");
            out.push_str("                Some(v) => Some(serde_json::from_value::<Input>(v).map_err(|e| proto_blue_xrpc::XrpcServerError::new(proto_blue_xrpc::ResponseType::InvalidRequest, format!(\"input deserialize: {e}\")))?),\n");
            out.push_str("                None => None,\n");
            out.push_str("            };\n");
        }
        // Build the handler call expression based on arg shape.
        let call = match (has_params, has_input) {
            (true, true) => "handler(ctx, params, input)",
            (true, false) => "handler(ctx, params)",
            (false, true) => "handler(ctx, input)",
            (false, false) => "handler(ctx)",
        };
        writeln!(out, "            let out = {call}.await?;").expect("infallible write to String");
        if has_output {
            out.push_str("            let value = serde_json::to_value(&out)\n");
            out.push_str("                .map_err(|e| proto_blue_xrpc::XrpcServerError::new(proto_blue_xrpc::ResponseType::InternalServerError, format!(\"output serialize: {e}\")))?;\n");
            out.push_str("            Ok::<_, proto_blue_xrpc::XrpcServerError>(value)\n");
        } else {
            out.push_str("            Ok::<_, proto_blue_xrpc::XrpcServerError>(out)\n");
        }
        out.push_str("        }\n");
        out.push_str("    })\n");
        out.push_str("}\n\n");
        if has_params && let Some(params) = &proc.parameters {
            Self::generate_params_from_ctx(out, params);
        }
    }

    /// Emit the helper that reads params out of a `HandlerContext`.
    /// Missing values just leave the field `None`; string-based
    /// coercion mirrors the TS `paramsParseLoose` default (numbers
    /// and booleans are accepted in string form, matching how an
    /// HTTP query string transports them).
    fn generate_params_from_ctx(out: &mut String, params: &LexXrpcParameters) {
        out.push_str("#[cfg(feature = \"server\")]\n");
        out.push_str(
            "fn params_from_ctx(ctx: &proto_blue_xrpc::HandlerContext) -> Option<Params> {\n",
        );
        out.push_str("    // Always construct a `Params` — required fields are\n");
        out.push_str("    // validated upstream by the lexicon validator when enabled;\n");
        out.push_str("    // missing values surface as runtime errors from the handler.\n");
        out.push_str("    Some(Params {\n");

        let mut prop_names: Vec<&String> = params.properties.keys().collect();
        prop_names.sort();
        let required: BTreeSet<&str> = params.required.iter().map(String::as_str).collect();

        for prop_name in prop_names {
            let prop = &params.properties[prop_name];
            let field = to_snake_case(prop_name);
            let key = prop_name;
            let is_required = required.contains(prop_name.as_str());

            // `match Some/None` form preferred over `Option::map_or_else`
            // here because the closure-and-default form expands to one
            // unreadable line per branch; the `match` keeps the parser
            // shapes visually aligned and the surrounding outer match
            // already establishes the structure.
            #[allow(clippy::option_if_let_else)]
            let parser = match prop {
                LexUserType::String(s) => match string_format_constructor(s.format.as_deref()) {
                    Some(ctor) => format!("ctx.params.get(\"{key}\").and_then(|v| {ctor}(v).ok())"),
                    None => format!("ctx.params.get(\"{key}\").cloned()"),
                },
                LexUserType::Integer(_) => {
                    format!("ctx.params.get(\"{key}\").and_then(|v| v.parse::<i64>().ok())")
                }
                LexUserType::Boolean(_) => {
                    format!("ctx.params.get(\"{key}\").and_then(|v| v.parse::<bool>().ok())")
                }
                LexUserType::Array(arr) => match &*arr.items {
                    LexUserType::String(s) => {
                        match string_format_constructor(s.format.as_deref()) {
                            Some(ctor) => format!(
                                "ctx.params.get(\"{key}\").and_then(|v| v.split(',').map({ctor}).collect::<Result<Vec<_>, _>>().ok())"
                            ),
                            None => format!(
                                "Some(ctx.params.get(\"{key}\").map(|v| v.split(',').map(String::from).collect::<Vec<_>>()).unwrap_or_default())"
                            ),
                        }
                    }
                    _ => format!("ctx.params.get(\"{key}\").cloned().map(|_| Vec::new())"),
                },
                _ => format!("ctx.params.get(\"{key}\").cloned()"),
            };

            if is_required {
                // required fields get the bare value (Option is
                // unwrapped with a default-ish fallback); upstream
                // lexicon validation should have caught absence.
                writeln!(out, "        {field}: ({parser})?,").expect("infallible write to String");
            } else {
                writeln!(out, "        {field}: {parser},").expect("infallible write to String");
            }
        }

        out.push_str("    })\n");
        out.push_str("}\n\n");
    }

    /// Emit a helper that converts `&Params` into a `QueryParams` map.
    ///
    /// Skips fields whose value is `None` so `skip_serializing_if =
    /// "Option::is_none"` semantics carry through to the wire.
    fn generate_to_query_params(out: &mut String, params: &LexXrpcParameters) {
        out.push_str("fn to_query_params(p: &Params) -> proto_blue_xrpc::QueryParams {\n");
        out.push_str("    let mut qp = proto_blue_xrpc::QueryParams::new();\n");

        let mut prop_names: Vec<&String> = params.properties.keys().collect();
        prop_names.sort();
        let required: BTreeSet<&str> = params.required.iter().map(String::as_str).collect();

        for prop_name in prop_names {
            let prop = &params.properties[prop_name];
            let field = to_snake_case(prop_name);
            let is_required = required.contains(prop_name.as_str());
            let key = prop_name;

            // Use `ToString::to_string` (Display) on the field so the same
            // template emission works for plain `String` (Display = identity)
            // and any of the validated `proto_blue_syntax::*` newtypes
            // (Display = the inner string). No special-casing per format.
            let conv = match prop {
                LexUserType::String(_) => {
                    "proto_blue_xrpc::QueryValue::String(v.to_string())".to_string()
                }
                LexUserType::Integer(_) => {
                    format!("proto_blue_xrpc::QueryValue::Integer({})", "*v")
                }
                LexUserType::Boolean(_) => {
                    format!("proto_blue_xrpc::QueryValue::Boolean({})", "*v")
                }
                LexUserType::Array(arr) => match &*arr.items {
                    LexUserType::String(_) => {
                        "proto_blue_xrpc::QueryValue::Array(v.iter().map(|x| proto_blue_xrpc::QueryValue::String(x.to_string())).collect())".to_string()
                    }
                    LexUserType::Integer(_) => {
                        "proto_blue_xrpc::QueryValue::Array(v.iter().map(|x| proto_blue_xrpc::QueryValue::Integer(*x)).collect())".to_string()
                    }
                    _ => {
                        "proto_blue_xrpc::QueryValue::String(String::new())".to_string()
                    }
                },
                _ => "proto_blue_xrpc::QueryValue::String(String::new())".to_string(),
            };

            if is_required {
                writeln!(
                    out,
                    "    {{ let v = &p.{field}; qp.insert(\"{key}\".to_string(), {conv}); }}"
                )
                .expect("infallible write to String");
            } else {
                writeln!(
                    out,
                    "    if let Some(v) = &p.{field} {{ qp.insert(\"{key}\".to_string(), {conv}); }}"
                )
                .expect("infallible write to String");
            }
        }

        out.push_str("    qp\n");
        out.push_str("}\n\n");
    }

    /// Generate a subscription.
    fn generate_subscription(
        out: &mut String,
        nsid: &str,
        _type_name: &str,
        sub: &LexXrpcSubscription,
    ) {
        let has_params = sub
            .parameters
            .as_ref()
            .is_some_and(|p| !p.properties.is_empty());
        // Post-parity-refactor (#46): `LexXrpcSubscription.message` now
        // carries a required `LexRefUnion` schema rather than the old
        // optional `LexXrpcBody`. The presence of a message is
        // determined solely by `sub.message.is_some()`.
        let has_message = sub.message.is_some();

        if has_params || has_message {
            if let Some(desc) = &sub.description {
                writeln!(out, "/// {}", escape_doc_text(desc)).expect("infallible write to String");
            }
            writeln!(out, "/// XRPC Subscription: {nsid}").expect("infallible write to String");
        }

        if let Some(params) = &sub.parameters
            && !params.properties.is_empty()
        {
            Self::generate_params(out, nsid, params);
        }

        if let Some(msg) = &sub.message {
            // Wrap the `LexRefUnion` back into a `LexUserType::Union`
            // so `generate_body_schema`'s existing union-codegen path
            // (tagged enum of boxed variants) can handle it unchanged.
            let union_def = LexUserType::Union(msg.schema.clone());
            Self::generate_body_schema(out, nsid, "Message", &union_def);
        }
    }

    /// Generate a Params struct from XRPC parameters.
    fn generate_params(out: &mut String, _nsid: &str, params: &LexXrpcParameters) {
        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        out.push_str("#[serde(rename_all = \"camelCase\")]\n");
        out.push_str("pub struct Params {\n");

        let mut prop_names: Vec<&String> = params.properties.keys().collect();
        prop_names.sort();
        let required: BTreeSet<&str> = params.required.iter().map(String::as_str).collect();
        let mut seen_idents: std::collections::HashSet<String> = std::collections::HashSet::new();

        for prop_name in prop_names {
            let prop_type = &params.properties[prop_name];
            let is_required = required.contains(prop_name.as_str());
            let raw_rust_name = to_snake_case(prop_name);
            let rust_name = disambiguate(&mut seen_idents, raw_rust_name.clone());
            let was_disambiguated = rust_name != raw_rust_name;
            let rust_type = Self::param_type_to_rust(prop_type);

            if was_disambiguated {
                writeln!(
                    out,
                    "    /// Renamed from `{prop_name}` to avoid a Rust identifier collision with a sibling param."
                )
                .expect("infallible write to String");
            }

            let needs_rename = rust_name != *prop_name && to_camel_case(&rust_name) != *prop_name;
            if needs_rename {
                writeln!(out, "    #[serde(rename = \"{prop_name}\")]")
                    .expect("infallible write to String");
            }

            if is_required {
                writeln!(out, "    pub {rust_name}: {rust_type},")
                    .expect("infallible write to String");
            } else {
                out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
                writeln!(out, "    pub {rust_name}: Option<{rust_type}>,")
                    .expect("infallible write to String");
            }
        }

        out.push_str("}\n\n");
    }

    /// Generate a struct from a body schema (input/output/message).
    fn generate_body_schema(out: &mut String, nsid: &str, name: &str, schema: &LexUserType) {
        match schema {
            LexUserType::Object(obj) => {
                Self::generate_object(out, nsid, name, obj, false);
            }
            LexUserType::Ref(r) => {
                let rust_type = Self::ref_to_rust(nsid, &r.ref_target);
                writeln!(out, "pub type {name} = {rust_type};")
                    .expect("infallible write to String");
                out.push('\n');
            }
            LexUserType::Union(union_def) => {
                Self::generate_union(out, nsid, name, union_def);
            }
            _ => {}
        }
    }

    /// Generate a Rust enum for a string with enum values.
    fn generate_string_enum(
        out: &mut String,
        type_name: &str,
        values: &[String],
        description: Option<&str>,
    ) {
        if let Some(desc) = description {
            writeln!(out, "/// {}", escape_doc_text(desc)).expect("infallible write to String");
        }
        out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n");
        writeln!(out, "pub enum {type_name} {{").expect("infallible write to String");

        let mut seen_variants: std::collections::HashSet<String> = std::collections::HashSet::new();
        for value in values {
            let raw_variant = to_pascal_case(value);
            let variant_name = disambiguate(&mut seen_variants, raw_variant.clone());
            let was_disambiguated = variant_name != raw_variant;

            if was_disambiguated {
                writeln!(
                    out,
                    "    /// Renamed from `{value}` to avoid a Rust variant collision with a sibling."
                )
                .expect("infallible write to String");
            }
            // serde rename when the wire form differs from the chosen
            // variant identifier (always the case after disambiguation).
            if variant_name != *value {
                writeln!(out, "    #[serde(rename = \"{value}\")]")
                    .expect("infallible write to String");
            }
            writeln!(out, "    {variant_name},").expect("infallible write to String");
        }

        out.push_str("}\n\n");
    }

    /// Generate known values as a type alias + constants.
    fn generate_known_values(
        out: &mut String,
        type_name: &str,
        values: &[String],
        description: Option<&str>,
    ) {
        if let Some(desc) = description {
            writeln!(out, "/// {}", escape_doc_text(desc)).expect("infallible write to String");
        }
        // Known values allow extension, so use String with named constants.
        writeln!(out, "pub type {type_name} = String;").expect("infallible write to String");

        // Values may be fully-qualified (e.g. "app.bsky.graph.defs#modlist")
        // — extract just the fragment after '#' if present for the const name.
        //
        // The constant identifier joins the type name and the fragment
        // in pure SCREAMING_SNAKE form (both pieces go through
        // `to_screaming_snake`) so the result is valid per Rust's
        // `non_upper_case_globals` lint — e.g. `ReasonType` +
        // `reason-violence-other` → `REASON_TYPE_REASON_VIOLENCE_OTHER`.
        let type_prefix = to_screaming_snake(type_name);
        let mut seen = BTreeSet::new();
        for value in values {
            let short = value
                .rsplit_once('#')
                .map_or(value.as_str(), |(_, frag)| frag);
            let const_name = to_screaming_snake(short);
            let full_name = format!("{type_prefix}_{const_name}");
            if seen.insert(full_name.clone()) {
                writeln!(out, "pub const {full_name}: &str = \"{value}\";")
                    .expect("infallible write to String");
            }
        }
        out.push('\n');
    }

    /// Generate a union enum.
    fn generate_union(out: &mut String, nsid: &str, type_name: &str, union_def: &LexRefUnion) {
        if let Some(desc) = &union_def.description {
            writeln!(out, "/// {}", escape_doc_text(desc)).expect("infallible write to String");
        }
        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        out.push_str("#[serde(tag = \"$type\")]\n");
        writeln!(out, "pub enum {type_name} {{").expect("infallible write to String");

        let mut seen_variants: std::collections::HashSet<String> = std::collections::HashSet::new();
        // Open unions also emit an `Other` variant below; reserve so a real
        // ref whose variant happens to be `Other` doesn't collide with it.
        if union_def.closed != Some(true) {
            seen_variants.insert("Other".to_string());
        }
        for ref_str in &union_def.refs {
            let (ref_nsid, ref_def) = parse_ref(nsid, ref_str);
            let raw_variant = ref_to_variant_name(&ref_nsid, &ref_def);
            let variant_name = disambiguate(&mut seen_variants, raw_variant.clone());
            let was_disambiguated = variant_name != raw_variant;
            let rust_type = Self::ref_to_rust(nsid, ref_str);
            let full_ref = if ref_def == "main" {
                ref_nsid.clone()
            } else {
                format!("{ref_nsid}#{ref_def}")
            };
            if was_disambiguated {
                writeln!(
                    out,
                    "    /// Renamed from `{raw_variant}` to avoid a Rust variant collision with a sibling."
                )
                .expect("infallible write to String");
            }
            writeln!(out, "    #[serde(rename = \"{full_ref}\")]")
                .expect("infallible write to String");
            writeln!(out, "    {variant_name}(Box<{rust_type}>),")
                .expect("infallible write to String");
        }

        // Open unions allow unknown types
        if union_def.closed != Some(true) {
            out.push_str("    #[serde(other)]\n");
            out.push_str("    Other,\n");
        }

        out.push_str("}\n\n");
    }

    /// Convert a Lexicon type to a Rust type string.
    ///
    /// String fields with a recognised `format` map to validated newtypes
    /// from `proto_blue_syntax` so the type system encodes the on-the-wire
    /// invariant (a DID-typed field really is a DID, etc.). `blob` maps to
    /// `proto_blue_lex_data::BlobRef` (the enum over typed + legacy forms
    /// from #32); `cid-link` maps to `proto_blue_lex_data::Cid`.
    fn type_to_rust(nsid: &str, ty: &LexUserType) -> String {
        match ty {
            LexUserType::String(s) => string_format_to_rust(s.format.as_deref()).to_string(),
            LexUserType::Integer(_) => "i64".to_string(),
            LexUserType::Boolean(_) => "bool".to_string(),
            LexUserType::Bytes(_) => "Vec<u8>".to_string(),
            LexUserType::CidLink(_) => "proto_blue_lex_data::Cid".to_string(),
            LexUserType::Blob(_) => "proto_blue_lex_data::BlobRef".to_string(),
            LexUserType::Array(arr) => {
                let inner = Self::type_to_rust(nsid, &arr.items);
                format!("Vec<{inner}>")
            }
            LexUserType::Ref(r) => Self::ref_to_rust(nsid, &r.ref_target),
            // `Unknown`, `Union` (when not synthesised inline), and any
            // future variant the lexicon grammar grows fall back to an
            // opaque JSON value. Collapsed via the wildcard so the three
            // identical bodies don't repeat.
            _ => "serde_json::Value".to_string(),
        }
    }

    /// Convert a param type to Rust.
    ///
    /// Mirrors `type_to_rust`'s `format`-aware mapping for `LexString`:
    /// string params with a recognised `format` are exposed as the
    /// validated `proto_blue_syntax` newtype rather than a bare `String`.
    /// The codegen-emitted `to_query_params` / `params_from_ctx` helpers
    /// pair this with `Display`-based serialisation and the syntax
    /// crate's `::new(&str) -> Result<_, _>` constructor for parsing,
    /// so wire-string ↔ typed-newtype round-trips work for any caller.
    fn param_type_to_rust(ty: &LexUserType) -> String {
        match ty {
            LexUserType::String(s) => string_format_to_rust(s.format.as_deref()).to_string(),
            LexUserType::Integer(_) => "i64".to_string(),
            LexUserType::Boolean(_) => "bool".to_string(),
            LexUserType::Array(arr) => {
                let inner = Self::param_type_to_rust(&arr.items);
                format!("Vec<{inner}>")
            }
            // `Unknown` and any other variant fall back to a plain `String`
            // because query params are wire-string already. Collapsed via
            // the wildcard so the two identical bodies don't repeat.
            _ => "String".to_string(),
        }
    }

    /// Convert a ref target to a Rust type path.
    fn ref_to_rust(current_nsid: &str, ref_target: &str) -> String {
        let (ref_nsid, ref_def) = parse_ref(current_nsid, ref_target);

        if ref_nsid == current_nsid {
            // Local reference within the same file
            def_name_to_type(&ref_def)
        } else {
            // Cross-module reference. NSID segments are usually
            // lowercase but the final method-name segment is often
            // camelCase (`getSession`, `createRecord`). The module
            // declaration in mod.rs renames those to snake_case via
            // `#[path]`, so cross-refs must use the snake form too.
            let parts: Vec<&str> = ref_nsid.split('.').collect();
            let module_path = parts
                .iter()
                .map(|p| sanitize_ident(&to_snake_case(p)))
                .collect::<Vec<_>>()
                .join("::");
            let type_name = def_name_to_type(&ref_def);
            format!("crate::{module_path}::{type_name}")
        }
    }
}

/// Source-code expression for the validating `::new(&str) -> Result<_, _>`
/// constructor of the newtype `string_format_to_rust` maps a given format
/// to. Returns `None` when the format is unmapped or absent — i.e. when
/// the param's Rust type is a plain `String`.
///
/// Used by the param-helper code paths (`to_query_params`,
/// `params_from_ctx`) to parse query-string values into the typed newtype
/// at the call boundary.
fn string_format_constructor(format: Option<&str>) -> Option<&'static str> {
    Some(match format {
        Some("did") => "proto_blue_syntax::Did::new",
        Some("handle") => "proto_blue_syntax::Handle::new",
        Some("at-identifier") => "proto_blue_syntax::AtIdentifier::new",
        Some("nsid") => "proto_blue_syntax::Nsid::new",
        Some("at-uri") => "proto_blue_syntax::AtUri::new",
        Some("tid") => "proto_blue_syntax::Tid::new",
        Some("record-key") => "proto_blue_syntax::RecordKey::new",
        Some("datetime") => "proto_blue_syntax::Datetime::new",
        _ => return None,
    })
}

/// Map a Lexicon `string` `format` value to a Rust type path.
///
/// Recognised formats use the validated newtypes from `proto_blue_syntax`
/// so a typed-string field's invariant (it really is a DID, NSID, etc.)
/// is enforced at the type system rather than left as runtime parsing
/// at every consumer. Unrecognised or absent formats fall back to
/// `String`.
///
/// Notes:
/// - `cid` falls back to `String` here because `LexUserType::CidLink` is
///   the lexicon's intended way to type a CID-as-link (the `cid-link`
///   user type), and `format: cid` on a plain string is rare and
///   semantically distinct (raw CID string, not a CBOR tag-42 link).
/// - `language` and `uri` keep `String` because their newtypes in
///   `proto_blue_syntax` don't currently impl serde's `Serialize` /
///   `Deserialize`, so emitting them in `#[derive(Serialize, Deserialize)]`
///   structs wouldn't compile. Promote in a follow-up once those traits land.
fn string_format_to_rust(format: Option<&str>) -> &'static str {
    match format {
        Some("did") => "proto_blue_syntax::Did",
        Some("handle") => "proto_blue_syntax::Handle",
        Some("at-identifier") => "proto_blue_syntax::AtIdentifier",
        Some("nsid") => "proto_blue_syntax::Nsid",
        Some("at-uri") => "proto_blue_syntax::AtUri",
        Some("tid") => "proto_blue_syntax::Tid",
        Some("record-key") => "proto_blue_syntax::RecordKey",
        Some("datetime") => "proto_blue_syntax::Datetime",
        // `cid` / `language` / `uri` and any other format: see fn doc.
        _ => "String",
    }
}

/// Join a parent directory with a child segment, used to look up
/// whether a child has further sub-children in `mod_tree`.
fn join_dir(dir: &str, child: &str) -> String {
    if dir.is_empty() {
        child.to_string()
    } else {
        format!("{dir}/{child}")
    }
}

// --- Naming utilities ---

/// Rewrite a lexicon description for emission as a rustdoc comment.
///
/// Two transformations:
///
/// 1. **Bare `http(s)` URLs** are wrapped in `<…>`. Rustdoc requires
///    URLs to be in angle brackets or backticks so they render as
///    automatic links, and lints bare URLs at `-D warnings`.
///    URLs already inside `<...>` in the source are passed through
///    unchanged so we don't end up with `<<url>>`.
///
/// 2. **Internal newlines** become `\n/// ` so a multi-line lexicon
///    description like `"First line.\nSecond line."` survives
///    embedding as `/// {desc}\n` without breaking rustc's parser.
///    Without this, the second line would be emitted as bare code
///    and rustc would fail with `error: expected one of '!' or '::'`
///    on whatever the description happens to start with (#25).
fn escape_doc_text(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = String::with_capacity(s.len());
    let mut i = 0;
    while i < bytes.len() {
        let rest = &s[i..];
        let scheme_len = if rest.starts_with("https://") {
            Some(8)
        } else if rest.starts_with("http://") {
            Some(7)
        } else {
            None
        };
        if let Some(n) = scheme_len {
            // Don't re-wrap a URL already inside `<...>` from the
            // source description.
            let already_wrapped = out.ends_with('<');
            let url_start = i;
            let mut url_end = i + n;
            while url_end < bytes.len() {
                let c = bytes[url_end];
                // Stop at whitespace or trailing punctuation that
                // typically terminates a URL in prose. Period,
                // comma, semicolon, colon, close-paren/bracket/brace
                // are the common cases; keep `#` and `?` in since
                // they're valid URL-internal chars.
                if c.is_ascii_whitespace() || matches!(c, b'<' | b'>') {
                    break;
                }
                url_end += 1;
            }
            // Trim trailing sentence punctuation off the URL.
            while url_end > url_start + n {
                let last = bytes[url_end - 1];
                if matches!(
                    last,
                    b'.' | b',' | b';' | b':' | b')' | b']' | b'}' | b'!' | b'?'
                ) {
                    url_end -= 1;
                } else {
                    break;
                }
            }
            if already_wrapped {
                out.push_str(&s[url_start..url_end]);
            } else {
                out.push('<');
                out.push_str(&s[url_start..url_end]);
                out.push('>');
            }
            i = url_end;
        } else {
            // Copy one char at a time; we can't rely on byte indexing
            // for multibyte chars, so advance by the char's utf8 len.
            let ch = rest.chars().next().unwrap();
            if ch == '\n' {
                // Continuation: every internal newline gets a `/// `
                // prefix on the next line so the wrapping `format!("/// {}\n", ...)`
                // at the call sites produces valid rustdoc.
                out.push_str("\n/// ");
            } else {
                out.push(ch);
            }
            i += ch.len_utf8();
        }
    }
    out
}

/// - `"#defName"` -> (`current_nsid`, `defName`)
/// - `"some.nsid#defName"` -> (`some.nsid`, `defName`)
/// - `"some.nsid"` -> (`some.nsid`, `main`)
//
// `option_if_let_else` would collapse the if-let / else-if-let / else
// chain into a nested `map_or_else` pair, which obscures the three-case
// structure (leading-`#`, embedded-`#`, no-`#`). Per-site judgment: keep
// the if-let cascade and silence the lint.
#[allow(clippy::option_if_let_else)]
fn parse_ref(current_nsid: &str, ref_str: &str) -> (String, String) {
    if let Some(suffix) = ref_str.strip_prefix('#') {
        (current_nsid.to_string(), suffix.to_string())
    } else if let Some(pos) = ref_str.find('#') {
        (ref_str[..pos].to_string(), ref_str[pos + 1..].to_string())
    } else {
        (ref_str.to_string(), "main".to_string())
    }
}

/// Convert a def name to a Rust type name (`PascalCase`).
/// Avoids conflicts with standard library types.
fn def_name_to_type(def_name: &str) -> String {
    if def_name == "main" {
        "Main".to_string()
    } else {
        let name = to_pascal_case(def_name);
        sanitize_type_name(&name)
    }
}

/// Ensure a type name doesn't conflict with standard library types.
fn sanitize_type_name(name: &str) -> String {
    match name {
        "Option" => "LexOption".to_string(),
        "Result" => "LexResult".to_string(),
        "Error" => "LexError".to_string(),
        "Box" => "LexBox".to_string(),
        "String" => "LexString".to_string(),
        "Vec" => "LexVec".to_string(),
        _ => name.to_string(),
    }
}

/// Generate a variant name for a union member.
///
/// Uses every NSID segment after the first (the top-level reverse-TLD
/// like `app` / `com`) to guarantee uniqueness across the 322-schema
/// registry. Previously only the last two segments were used, which
/// collided for cross-namespace names like
/// `app.bsky.feed.defs#postView` vs `app.bsky.unspecced.defs#postView`
/// (both would produce `DefsPostView`). Now they become
/// `BskyFeedDefsPostView` and `BskyUnspeccedDefsPostView` respectively.
fn ref_to_variant_name(nsid: &str, def_name: &str) -> String {
    let parts: Vec<&str> = nsid.split('.').collect();
    let suffix = if def_name == "main" {
        String::new()
    } else {
        to_pascal_case(def_name)
    };

    // Skip the reverse-TLD root (e.g. `app`, `com`) when the path has
    // enough depth to distinguish meaningfully without it; otherwise
    // fall back to the whole path.
    let ns_segments: Vec<String> = if parts.len() > 2 {
        parts[1..].iter().map(|p| to_pascal_case(p)).collect()
    } else {
        parts.iter().map(|p| to_pascal_case(p)).collect()
    };
    let ns: String = ns_segments.concat();

    format!("{ns}{suffix}")
}

/// Convert a string to `PascalCase`.
fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for ch in s.chars() {
        if !ch.is_ascii_alphanumeric() {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(ch.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(ch);
        }
    }

    // Ensure it starts with uppercase
    if let Some(first) = result.chars().next() {
        if first.is_ascii_digit() {
            result = format!("V{result}");
        }
    }

    result
}

/// Convert a string to `snake_case`.
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    let mut prev_was_upper = false;

    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i > 0 && !prev_was_upper {
                result.push('_');
            }
            result.push(ch.to_ascii_lowercase());
            prev_was_upper = true;
        } else if ch == '-' || ch == '.' || ch == '#' {
            result.push('_');
            prev_was_upper = false;
        } else if !ch.is_ascii_alphanumeric() && ch != '_' {
            // Strip non-alphanumeric chars like '!'
            prev_was_upper = false;
        } else {
            prev_was_upper = false;
            result.push(ch);
        }
    }

    sanitize_ident(&result)
}

/// Convert `snake_case` back to `camelCase` for comparison.
fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;

    for ch in s.chars() {
        if ch == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(ch.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(ch);
        }
    }
    result
}

/// Convert a string to `SCREAMING_SNAKE_CASE`.
fn to_screaming_snake(s: &str) -> String {
    let snake = to_snake_case(s);
    snake.to_ascii_uppercase()
}

/// Sanitize a Rust identifier, escaping keywords.
///
/// Covers:
/// - Rust 2018/2021 strict keywords
/// - Rust 2024 keywords (`gen`, `try`)
/// - Reserved-for-future keywords (`priv`, `abstract`, `become`, `box`, `do`,
///   `final`, `macro`, `override`, `typeof`, `virtual`, `yield`)
/// - Weak/contextual keywords that are safer to escape than gamble on
///   future hard reservations (`union`, `dyn` was promoted in 2018, `async`
///   / `await` were promoted in 2018; `gen` / `try` were promoted in 2024
///   per <https://doc.rust-lang.org/reference/keywords.html>).
///
/// Anything not in the list passes through unmodified.
fn sanitize_ident(s: &str) -> String {
    let s = s.replace('-', "_");
    match s.as_str() {
        // 2015/2018/2021 strict
        "as" | "break" | "const" | "continue" | "crate" | "else" | "enum" | "extern"
        | "false" | "fn" | "for" | "if" | "impl" | "in" | "let" | "loop" | "match" | "mod"
        | "move" | "mut" | "pub" | "ref" | "return" | "self" | "Self" | "static" | "struct"
        | "super" | "trait" | "true" | "type" | "unsafe" | "use" | "where" | "while"
        // promoted in 2018
        | "async" | "await" | "dyn"
        // promoted in 2024
        | "gen" | "try"
        // reserved-for-future
        | "abstract" | "become" | "box" | "do" | "final" | "macro" | "override" | "priv"
        | "typeof" | "unsized" | "virtual" | "yield"
        // weak / future-reservation candidates — safer to escape than gamble
        | "union" => format!("r#{s}"),
        _ => s,
    }
}

/// Disambiguate `candidate` against already-emitted identifiers.
///
/// If `candidate` is unique in `seen`, inserts and returns it unchanged.
/// Otherwise appends `_2`, `_3`, ... until a free form is found, inserts
/// the resulting name, and returns it.
///
/// Used by the field/variant emission sites to keep generated structs
/// and enums valid Rust even when two source names sanitize to the same
/// identifier (e.g. `myField` and `my_field` both → `my_field`, or
/// `type` and a literal `r#type` field both → `r#type`). Each colliding
/// field still serdes via its original wire name through a `serde(rename)`
/// attribute the caller emits.
fn disambiguate(seen: &mut std::collections::HashSet<String>, candidate: String) -> String {
    if seen.insert(candidate.clone()) {
        return candidate;
    }
    let mut n: u32 = 2;
    loop {
        let alt = format!("{candidate}_{n}");
        if seen.insert(alt.clone()) {
            return alt;
        }
        n = n
            .checked_add(1)
            .expect("identifier disambiguation counter overflow (>4 billion siblings)");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("main"), "Main");
        assert_eq!(to_pascal_case("profileView"), "ProfileView");
        assert_eq!(to_pascal_case("feed-view-post"), "FeedViewPost");
        assert_eq!(to_pascal_case("getProfile"), "GetProfile");
    }

    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("createdAt"), "created_at");
        assert_eq!(to_snake_case("displayName"), "display_name");
        assert_eq!(to_snake_case("did"), "did");
        assert_eq!(to_snake_case("uri"), "uri");
    }

    #[test]
    fn test_to_camel_case() {
        assert_eq!(to_camel_case("created_at"), "createdAt");
        assert_eq!(to_camel_case("display_name"), "displayName");
    }

    #[test]
    fn test_sanitize_ident() {
        assert_eq!(sanitize_ident("type"), "r#type");
        assert_eq!(sanitize_ident("self"), "r#self");
        assert_eq!(sanitize_ident("normal"), "normal");
        assert_eq!(sanitize_ident("feed-view"), "feed_view");
    }

    /// Edition-2024 strict keywords (`gen`, `try`) must be escaped.
    /// Reserved-for-future words (`abstract`, `become`, `box`, `do`,
    /// `final`, `macro`, `override`, `priv`, `typeof`, `unsized`,
    /// `virtual`, `yield`) must be escaped. The weak/contextual `union`
    /// is included defensively. Regression test for #5.
    #[test]
    fn test_sanitize_ident_edition_2024_and_reserved() {
        // Edition 2024 hard keywords.
        assert_eq!(sanitize_ident("gen"), "r#gen");
        assert_eq!(sanitize_ident("try"), "r#try");

        // Reserved-for-future / unused.
        for kw in [
            "abstract", "become", "box", "do", "final", "macro", "override", "priv", "typeof",
            "unsized", "virtual", "yield",
        ] {
            assert_eq!(sanitize_ident(kw), format!("r#{kw}"), "{kw} should escape");
        }

        // Weak / contextually reserved.
        assert_eq!(sanitize_ident("union"), "r#union");
        assert_eq!(sanitize_ident("dyn"), "r#dyn");

        // Plain identifiers and dash-bearing names still pass through unmodified.
        assert_eq!(sanitize_ident("genuine"), "genuine");
        assert_eq!(sanitize_ident("trying"), "trying");
        assert_eq!(sanitize_ident("union-type"), "union_type");
    }

    #[test]
    fn test_disambiguate_returns_candidate_when_unique() {
        let mut seen = std::collections::HashSet::new();
        assert_eq!(disambiguate(&mut seen, "foo".to_string()), "foo");
        assert!(seen.contains("foo"));
    }

    #[test]
    fn test_disambiguate_appends_suffix_on_collision() {
        let mut seen = std::collections::HashSet::new();
        seen.insert("foo".to_string());
        assert_eq!(disambiguate(&mut seen, "foo".to_string()), "foo_2");
        assert_eq!(disambiguate(&mut seen, "foo".to_string()), "foo_3");
        assert_eq!(disambiguate(&mut seen, "bar".to_string()), "bar");
        assert_eq!(disambiguate(&mut seen, "foo_2".to_string()), "foo_2_2");
    }

    /// Build a `LexUserType::String` with all options unset.
    #[cfg(test)]
    fn mk_lex_string() -> proto_blue_lexicon::types::LexUserType {
        use proto_blue_lexicon::types::{LexString, LexUserType};
        LexUserType::String(LexString {
            description: None,
            format: None,
            min_length: None,
            max_length: None,
            min_graphemes: None,
            max_graphemes: None,
            enum_values: None,
            const_value: None,
            default: None,
            known_values: None,
        })
    }

    /// End-to-end: a synthetic `LexObject` whose properties collide after
    /// snake_case sanitization (`myField` and `my_field` both → `my_field`)
    /// must produce valid, distinct Rust field names with serde renames so
    /// the wire form round-trips. Regression test for #5.
    #[test]
    fn collision_in_object_produces_disambiguated_fields() {
        use proto_blue_lexicon::types::{LexObject, LexUserType};
        use std::collections::HashMap;

        let mut props: HashMap<String, LexUserType> = HashMap::new();
        props.insert("myField".to_string(), mk_lex_string());
        props.insert("my_field".to_string(), mk_lex_string());
        let obj = LexObject {
            description: None,
            properties: props,
            required: vec!["myField".to_string(), "my_field".to_string()],
            nullable: vec![],
        };
        let mut out = String::new();
        Generator::generate_object(&mut out, "x.y.z", "Synth", &obj, false);

        // Both fields must appear with distinct names. The struct carries
        // `serde(rename_all = "camelCase")`, so `pub my_field` already
        // serdes as wire-name `myField` without an explicit rename; only
        // the disambiguated field needs an explicit serde rename, and it
        // must point at the wire form (`my_field`) the source-order-second
        // property carried.
        assert!(
            out.contains("pub my_field: "),
            "first field stays `my_field`:\n{out}"
        );
        assert!(
            out.contains("pub my_field_2: "),
            "second field gets `_2` suffix:\n{out}"
        );
        assert!(
            out.contains("#[serde(rename = \"my_field\")]"),
            "disambiguated field carries an explicit serde rename to its wire name:\n{out}",
        );
        assert!(
            out.contains("Renamed from `my_field`"),
            "disambiguation doc-comment present:\n{out}",
        );
    }

    /// An object with an inline `union` property must emit a synthesised
    /// sum-type enum as a sibling and reference it by name in the field,
    /// instead of falling back to `serde_json::Value`. Regression test
    /// for #4 (audit's "unions emit serde_json::Value" finding).
    #[test]
    fn inline_union_property_emits_synthetic_sum_type() {
        use proto_blue_lexicon::types::{LexObject, LexRefUnion, LexUserType};
        use std::collections::HashMap;

        let mut props = HashMap::new();
        props.insert(
            "embed".to_string(),
            LexUserType::Union(LexRefUnion {
                description: None,
                refs: vec![
                    "app.bsky.embed.images".to_string(),
                    "app.bsky.embed.video".to_string(),
                ],
                closed: Some(false),
            }),
        );
        let obj = LexObject {
            description: None,
            properties: props,
            required: vec![],
            nullable: vec![],
        };
        let mut out = String::new();
        Generator::generate_object(&mut out, "app.bsky.feed.post", "Main", &obj, false);

        // The synthetic enum is emitted as a sibling with the convention
        // <TypeName><PropertyPascalCase>Refs (the suffix avoids colliding
        // with same-named top-level defs in the same module).
        assert!(
            out.contains("pub enum MainEmbedRefs {"),
            "expected synthetic `MainEmbedRefs` enum:\n{out}"
        );
        // Each ref becomes a variant.
        assert!(
            out.contains("Box<crate::app::bsky::embed::images::Main>"),
            "expected variant typed as Box<crate::app::bsky::embed::images::Main>:\n{out}"
        );
        // The struct field references the synthetic name, NOT serde_json::Value.
        assert!(
            out.contains("pub embed: Option<MainEmbedRefs>"),
            "expected struct field `embed: Option<MainEmbedRefs>`:\n{out}"
        );
        assert!(
            !out.contains("Option<serde_json::Value>"),
            "no serde_json::Value fallback should remain:\n{out}"
        );
    }

    /// An object with an `array<union>` property must emit the sum-type
    /// enum (named `<TypeName><PropertyPascalCase>Item`) and reference it
    /// inside `Vec<...>`. Regression test for #4 — the audit's smoking
    /// gun was unions-as-`serde_json::Value`; this nested case is just
    /// as relevant.
    #[test]
    fn array_of_union_emits_synthetic_sum_type_with_item_suffix() {
        use proto_blue_lexicon::types::{LexArray, LexObject, LexRefUnion, LexUserType};
        use std::collections::HashMap;

        let mut props = HashMap::new();
        props.insert(
            "facets".to_string(),
            LexUserType::Array(LexArray {
                description: None,
                items: Box::new(LexUserType::Union(LexRefUnion {
                    description: None,
                    refs: vec![
                        "app.bsky.richtext.facet#mention".to_string(),
                        "app.bsky.richtext.facet#link".to_string(),
                    ],
                    closed: Some(false),
                })),
                min_length: None,
                max_length: None,
            }),
        );
        let obj = LexObject {
            description: None,
            properties: props,
            required: vec!["facets".to_string()],
            nullable: vec![],
        };
        let mut out = String::new();
        Generator::generate_object(&mut out, "app.bsky.feed.post", "Main", &obj, false);

        // The synthetic enum carries `ItemRefs` — `Item` because the
        // union sits inside a `Vec`, `Refs` to disambiguate from any
        // same-named top-level def.
        assert!(
            out.contains("pub enum MainFacetsItemRefs {"),
            "expected synthetic `MainFacetsItemRefs` enum:\n{out}"
        );
        // The required, non-nullable field is `Vec<MainFacetsItemRefs>`.
        assert!(
            out.contains("pub facets: Vec<MainFacetsItemRefs>"),
            "expected `pub facets: Vec<MainFacetsItemRefs>`:\n{out}"
        );
    }

    /// A lexicon field literally named `gen` (a Rust 2024 keyword) must
    /// emit as `r#gen`. Regression test for #5 — the previous keyword
    /// list missed this and would have produced uncompilable Rust.
    #[test]
    fn edition_2024_keyword_field_emits_raw_ident() {
        use proto_blue_lexicon::types::LexObject;
        use std::collections::HashMap;

        let mut props = HashMap::new();
        props.insert("gen".to_string(), mk_lex_string());
        let obj = LexObject {
            description: None,
            properties: props,
            required: vec!["gen".to_string()],
            nullable: vec![],
        };
        let mut out = String::new();
        Generator::generate_object(&mut out, "x.y.z", "Synth", &obj, false);
        assert!(
            out.contains("pub r#gen: "),
            "edition-2024 keyword `gen` must emit raw-ident:\n{out}",
        );
    }

    #[test]
    fn test_parse_ref() {
        let (nsid, def) = parse_ref("app.bsky.feed.post", "#replyRef");
        assert_eq!(nsid, "app.bsky.feed.post");
        assert_eq!(def, "replyRef");

        let (nsid, def) = parse_ref("app.bsky.feed.post", "app.bsky.actor.defs#profileView");
        assert_eq!(nsid, "app.bsky.actor.defs");
        assert_eq!(def, "profileView");

        let (nsid, def) = parse_ref("app.bsky.feed.post", "app.bsky.embed.images");
        assert_eq!(nsid, "app.bsky.embed.images");
        assert_eq!(def, "main");
    }

    #[test]
    fn test_def_name_to_type() {
        assert_eq!(def_name_to_type("main"), "Main");
        assert_eq!(def_name_to_type("profileView"), "ProfileView");
        assert_eq!(def_name_to_type("feedViewPost"), "FeedViewPost");
    }

    #[test]
    fn test_ref_to_variant_name() {
        // Drops the reverse-TLD root (app/com) to reduce noise while
        // keeping every remaining segment so cross-namespace name
        // collisions can't happen.
        assert_eq!(
            ref_to_variant_name("app.bsky.embed.images", "main"),
            "BskyEmbedImages"
        );
        assert_eq!(
            ref_to_variant_name("app.bsky.embed.external", "main"),
            "BskyEmbedExternal"
        );
        assert_eq!(
            ref_to_variant_name("app.bsky.actor.defs", "profileView"),
            "BskyActorDefsProfileView"
        );
    }

    #[test]
    fn test_ref_to_variant_name_disambiguates_cross_namespace() {
        // The collision case the #45 parity audit flagged:
        // `app.bsky.feed.defs#postView` and
        // `app.bsky.unspecced.defs#postView` both used to produce
        // `DefsPostView`. They must now be distinct.
        let a = ref_to_variant_name("app.bsky.feed.defs", "postView");
        let b = ref_to_variant_name("app.bsky.unspecced.defs", "postView");
        assert_ne!(
            a, b,
            "cross-namespace collision must not produce the same variant"
        );
        assert_eq!(a, "BskyFeedDefsPostView");
        assert_eq!(b, "BskyUnspeccedDefsPostView");
    }

    #[test]
    fn test_to_screaming_snake() {
        assert_eq!(to_screaming_snake("active"), "ACTIVE");
        assert_eq!(to_screaming_snake("takedown"), "TAKEDOWN");
        assert_eq!(to_screaming_snake("content-media"), "CONTENT_MEDIA");
    }

    /// Regression test for #25: lexicon descriptions with internal `\n`
    /// must emit a `///` continuation on each subsequent line so the
    /// wrapping `format!("/// {}\n", escape_doc_text(desc))` at the call
    /// site produces valid rustdoc rather than bare code.
    #[test]
    fn escape_doc_text_inserts_continuation_on_newlines() {
        let escaped = escape_doc_text("First line.\nSecond line.");
        assert_eq!(escaped, "First line.\n/// Second line.");

        // Multi-paragraph (blank line between) survives — the empty
        // continuation line is still a valid (empty) rustdoc line.
        let multi = escape_doc_text("Para one.\n\nPara two.");
        assert_eq!(multi, "Para one.\n/// \n/// Para two.");

        // Single-line descriptions are passed through unchanged (modulo
        // any URL wrapping, which is the helper's other job).
        let plain = escape_doc_text("No newlines here.");
        assert_eq!(plain, "No newlines here.");
    }
}
