//! Core code generation: Lexicon types -> Rust source.

use std::collections::{BTreeMap, BTreeSet};

use proto_blue_lexicon::types::*;

/// Code generator that converts Lexicon documents to Rust source files.
pub struct Generator<'a> {
    docs: &'a [LexiconDoc],
}

impl<'a> Generator<'a> {
    pub fn new(docs: &'a [LexiconDoc]) -> Self {
        Generator { docs }
    }

    /// Generate all Rust source files. Returns a map of relative path -> content.
    pub fn generate(&self) -> BTreeMap<String, String> {
        let mut files = BTreeMap::new();

        // Track module tree for mod.rs generation
        // Key: directory path, Value: set of child module names
        let mut mod_tree: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();

        for doc in self.docs {
            let nsid = &doc.id;
            // Convert NSID to file path: app.bsky.feed.post -> app/bsky/feed/post.rs
            let parts: Vec<&str> = nsid.split('.').collect();
            if parts.len() < 2 {
                continue;
            }
            let file_path = format!("{}.rs", parts.join("/"));

            // Register in module tree
            for i in 0..parts.len() {
                let dir = if i == 0 {
                    String::new()
                } else {
                    parts[..i].join("/")
                };
                let child = parts[i];
                mod_tree.entry(dir).or_default().insert(child.to_string());
            }

            // Generate the file content
            let content = self.generate_file(doc);
            files.insert(file_path, content);
        }

        // Generate mod.rs files for each directory
        for (dir, children) in &mod_tree {
            let mod_path = if dir.is_empty() {
                "mod.rs".to_string()
            } else {
                format!("{}/mod.rs", dir)
            };

            // Only include children that are directories (have their own children)
            // or are leaf modules (have .rs files)
            let mut mod_content = String::new();
            mod_content.push_str("// Generated by atproto-codegen. Do not edit.\n\n");

            let mut child_list: Vec<&String> = children.iter().collect();
            child_list.sort();

            for child in child_list {
                let child_ident = sanitize_ident(child);
                mod_content.push_str(&format!("pub mod {child_ident};\n"));
            }

            files.insert(mod_path, mod_content);
        }

        files
    }

    /// Generate a single Rust source file for a lexicon document.
    fn generate_file(&self, doc: &LexiconDoc) -> String {
        let mut out = String::new();
        let nsid = &doc.id;

        out.push_str("// Generated by atproto-codegen. Do not edit.\n");
        out.push_str(&format!("//! Lexicon: {nsid}\n\n"));
        out.push_str("use serde::{Deserialize, Serialize};\n\n");

        // Sort defs for deterministic output
        let mut def_names: Vec<&String> = doc.defs.keys().collect();
        def_names.sort();

        for def_name in def_names {
            let def = &doc.defs[def_name];
            self.generate_def(&mut out, nsid, def_name, def);
        }

        out
    }

    /// Generate Rust code for a single definition.
    fn generate_def(&self, out: &mut String, nsid: &str, def_name: &str, def: &LexUserType) {
        let type_name = def_name_to_type(def_name);

        match def {
            LexUserType::Record(rec) => {
                self.generate_object(out, nsid, &type_name, &rec.record, true);
            }
            LexUserType::Object(obj) => {
                self.generate_object(out, nsid, &type_name, obj, false);
            }
            LexUserType::Query(query) => {
                self.generate_query(out, nsid, &type_name, query);
            }
            LexUserType::Procedure(proc) => {
                self.generate_procedure(out, nsid, &type_name, proc);
            }
            LexUserType::Subscription(sub) => {
                self.generate_subscription(out, nsid, &type_name, sub);
            }
            LexUserType::Array(arr) => {
                // Top-level array definitions get a type alias
                let inner = self.type_to_rust(nsid, &arr.items);
                if let Some(desc) = &arr.description {
                    out.push_str(&format!("/// {desc}\n"));
                }
                out.push_str(&format!("pub type {type_name} = Vec<{inner}>;\n\n"));
            }
            LexUserType::String(s) => {
                if let Some(enum_values) = &s.enum_values {
                    self.generate_string_enum(
                        out,
                        &type_name,
                        enum_values,
                        s.description.as_deref(),
                    );
                } else if let Some(known_values) = &s.known_values {
                    self.generate_known_values(
                        out,
                        &type_name,
                        known_values,
                        s.description.as_deref(),
                    );
                }
                // Plain strings don't need a type alias
            }
            LexUserType::Token(t) => {
                if let Some(desc) = &t.description {
                    out.push_str(&format!("/// {desc}\n"));
                }
                out.push_str(&format!(
                    "pub const {}: &str = \"{nsid}#{def_name}\";\n\n",
                    to_screaming_snake(&type_name)
                ));
            }
            LexUserType::Union(union_def) => {
                self.generate_union(out, nsid, &type_name, union_def);
            }
            // Other types don't generate standalone definitions
            _ => {}
        }
    }

    /// Generate a Rust struct for a Lexicon object.
    fn generate_object(
        &self,
        out: &mut String,
        nsid: &str,
        type_name: &str,
        obj: &LexObject,
        _is_record: bool,
    ) {
        if let Some(desc) = &obj.description {
            if !desc.is_empty() {
                out.push_str(&format!("/// {desc}\n"));
            }
        }
        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        out.push_str("#[serde(rename_all = \"camelCase\")]\n");
        out.push_str(&format!("pub struct {type_name} {{\n"));

        // Sort properties for deterministic output
        let mut prop_names: Vec<&String> = obj.properties.keys().collect();
        prop_names.sort();

        let required: BTreeSet<&str> = obj.required.iter().map(|s| s.as_str()).collect();
        let nullable: BTreeSet<&str> = obj.nullable.iter().map(|s| s.as_str()).collect();

        for prop_name in prop_names {
            let prop_type = &obj.properties[prop_name];
            let is_required = required.contains(prop_name.as_str());
            let is_nullable = nullable.contains(prop_name.as_str());

            let rust_name = to_snake_case(prop_name);
            let rust_type = self.type_to_rust(nsid, prop_type);

            // Add serde rename if snake_case differs from camelCase
            let needs_rename = rust_name != *prop_name && to_camel_case(&rust_name) != *prop_name;
            if needs_rename {
                out.push_str(&format!("    #[serde(rename = \"{prop_name}\")]\n"));
            }

            if is_required {
                if is_nullable {
                    out.push_str(&format!("    pub {rust_name}: Option<{rust_type}>,\n"));
                } else {
                    out.push_str(&format!("    pub {rust_name}: {rust_type},\n"));
                }
            } else {
                out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
                out.push_str(&format!("    pub {rust_name}: Option<{rust_type}>,\n"));
            }
        }

        out.push_str("}\n\n");
    }

    /// Generate a query (GET endpoint).
    fn generate_query(&self, out: &mut String, nsid: &str, _type_name: &str, query: &LexXrpcQuery) {
        let has_params = query
            .parameters
            .as_ref()
            .is_some_and(|p| !p.properties.is_empty());
        let has_output = query.output.as_ref().is_some_and(|o| o.schema.is_some());

        // Only emit doc comment if we're generating something after it
        if has_params || has_output {
            if let Some(desc) = &query.description {
                out.push_str(&format!("/// {desc}\n"));
            }
            out.push_str(&format!("/// XRPC Query: {nsid}\n"));
        }

        if let Some(params) = &query.parameters {
            if !params.properties.is_empty() {
                self.generate_params(out, nsid, params);
            }
        }

        if let Some(output) = &query.output {
            if let Some(schema) = &output.schema {
                self.generate_body_schema(out, nsid, "Output", schema);
            }
        }
    }

    /// Generate a procedure (POST endpoint).
    fn generate_procedure(
        &self,
        out: &mut String,
        nsid: &str,
        _type_name: &str,
        proc: &LexXrpcProcedure,
    ) {
        let has_params = proc
            .parameters
            .as_ref()
            .is_some_and(|p| !p.properties.is_empty());
        let has_input = proc.input.as_ref().is_some_and(|i| i.schema.is_some());
        let has_output = proc.output.as_ref().is_some_and(|o| o.schema.is_some());

        if has_params || has_input || has_output {
            if let Some(desc) = &proc.description {
                out.push_str(&format!("/// {desc}\n"));
            }
            out.push_str(&format!("/// XRPC Procedure: {nsid}\n"));
        }

        if let Some(params) = &proc.parameters {
            if !params.properties.is_empty() {
                self.generate_params(out, nsid, params);
            }
        }

        if let Some(input) = &proc.input {
            if let Some(schema) = &input.schema {
                self.generate_body_schema(out, nsid, "Input", schema);
            }
        }

        if let Some(output) = &proc.output {
            if let Some(schema) = &output.schema {
                self.generate_body_schema(out, nsid, "Output", schema);
            }
        }
    }

    /// Generate a subscription.
    fn generate_subscription(
        &self,
        out: &mut String,
        nsid: &str,
        _type_name: &str,
        sub: &LexXrpcSubscription,
    ) {
        let has_params = sub
            .parameters
            .as_ref()
            .is_some_and(|p| !p.properties.is_empty());
        let has_message = sub.message.as_ref().is_some_and(|m| m.schema.is_some());

        if has_params || has_message {
            if let Some(desc) = &sub.description {
                out.push_str(&format!("/// {desc}\n"));
            }
            out.push_str(&format!("/// XRPC Subscription: {nsid}\n"));
        }

        if let Some(params) = &sub.parameters {
            if !params.properties.is_empty() {
                self.generate_params(out, nsid, params);
            }
        }

        if let Some(msg) = &sub.message {
            if let Some(schema) = &msg.schema {
                self.generate_body_schema(out, nsid, "Message", schema);
            }
        }
    }

    /// Generate a Params struct from XRPC parameters.
    fn generate_params(&self, out: &mut String, _nsid: &str, params: &LexXrpcParameters) {
        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        out.push_str("#[serde(rename_all = \"camelCase\")]\n");
        out.push_str("pub struct Params {\n");

        let mut prop_names: Vec<&String> = params.properties.keys().collect();
        prop_names.sort();
        let required: BTreeSet<&str> = params.required.iter().map(|s| s.as_str()).collect();

        for prop_name in prop_names {
            let prop_type = &params.properties[prop_name];
            let is_required = required.contains(prop_name.as_str());
            let rust_name = to_snake_case(prop_name);
            let rust_type = self.param_type_to_rust(prop_type);

            let needs_rename = rust_name != *prop_name && to_camel_case(&rust_name) != *prop_name;
            if needs_rename {
                out.push_str(&format!("    #[serde(rename = \"{prop_name}\")]\n"));
            }

            if is_required {
                out.push_str(&format!("    pub {rust_name}: {rust_type},\n"));
            } else {
                out.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
                out.push_str(&format!("    pub {rust_name}: Option<{rust_type}>,\n"));
            }
        }

        out.push_str("}\n\n");
    }

    /// Generate a struct from a body schema (input/output/message).
    fn generate_body_schema(&self, out: &mut String, nsid: &str, name: &str, schema: &LexUserType) {
        match schema {
            LexUserType::Object(obj) => {
                self.generate_object(out, nsid, name, obj, false);
            }
            LexUserType::Ref(r) => {
                let rust_type = self.ref_to_rust(nsid, &r.ref_target);
                out.push_str(&format!("pub type {name} = {rust_type};\n\n"));
            }
            LexUserType::Union(union_def) => {
                self.generate_union(out, nsid, name, union_def);
            }
            _ => {}
        }
    }

    /// Generate a Rust enum for a string with enum values.
    fn generate_string_enum(
        &self,
        out: &mut String,
        type_name: &str,
        values: &[String],
        description: Option<&str>,
    ) {
        if let Some(desc) = description {
            out.push_str(&format!("/// {desc}\n"));
        }
        out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n");
        out.push_str(&format!("pub enum {type_name} {{\n"));

        for value in values {
            let variant_name = to_pascal_case(value);
            if variant_name != *value {
                out.push_str(&format!("    #[serde(rename = \"{value}\")]\n"));
            }
            out.push_str(&format!("    {variant_name},\n"));
        }

        out.push_str("}\n\n");
    }

    /// Generate known values as a type alias + constants.
    fn generate_known_values(
        &self,
        out: &mut String,
        type_name: &str,
        values: &[String],
        description: Option<&str>,
    ) {
        if let Some(desc) = description {
            out.push_str(&format!("/// {desc}\n"));
        }
        // Known values allow extension, so use String with named constants.
        out.push_str(&format!("pub type {type_name} = String;\n"));

        // Values may be fully-qualified (e.g. "app.bsky.graph.defs#modlist")
        // — extract just the fragment after '#' if present for the const name.
        let mut seen = BTreeSet::new();
        for value in values {
            let short = value
                .rsplit_once('#')
                .map(|(_, frag)| frag)
                .unwrap_or(value);
            let const_name = to_screaming_snake(short);
            let full_name = format!("{type_name}_{const_name}");
            if seen.insert(full_name.clone()) {
                out.push_str(&format!("pub const {full_name}: &str = \"{value}\";\n"));
            }
        }
        out.push('\n');
    }

    /// Generate a union enum.
    fn generate_union(
        &self,
        out: &mut String,
        nsid: &str,
        type_name: &str,
        union_def: &LexRefUnion,
    ) {
        if let Some(desc) = &union_def.description {
            out.push_str(&format!("/// {desc}\n"));
        }
        out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
        out.push_str("#[serde(tag = \"$type\")]\n");
        out.push_str(&format!("pub enum {type_name} {{\n"));

        for ref_str in &union_def.refs {
            let (ref_nsid, ref_def) = parse_ref(nsid, ref_str);
            let variant_name = ref_to_variant_name(&ref_nsid, &ref_def);
            let rust_type = self.ref_to_rust(nsid, ref_str);
            let full_ref = if ref_def == "main" {
                ref_nsid.clone()
            } else {
                format!("{ref_nsid}#{ref_def}")
            };
            out.push_str(&format!("    #[serde(rename = \"{full_ref}\")]\n"));
            out.push_str(&format!("    {variant_name}(Box<{rust_type}>),\n"));
        }

        // Open unions allow unknown types
        if union_def.closed != Some(true) {
            out.push_str("    #[serde(other)]\n");
            out.push_str("    Other,\n");
        }

        out.push_str("}\n\n");
    }

    /// Convert a Lexicon type to a Rust type string.
    fn type_to_rust(&self, nsid: &str, ty: &LexUserType) -> String {
        match ty {
            LexUserType::String(_) => "String".to_string(),
            LexUserType::Integer(_) => "i64".to_string(),
            LexUserType::Boolean(_) => "bool".to_string(),
            LexUserType::Bytes(_) => "Vec<u8>".to_string(),
            LexUserType::CidLink(_) => "String".to_string(),
            LexUserType::Blob(_) => "serde_json::Value".to_string(),
            LexUserType::Unknown(_) => "serde_json::Value".to_string(),
            LexUserType::Array(arr) => {
                let inner = self.type_to_rust(nsid, &arr.items);
                format!("Vec<{inner}>")
            }
            LexUserType::Ref(r) => self.ref_to_rust(nsid, &r.ref_target),
            LexUserType::Union(_) => "serde_json::Value".to_string(),
            _ => "serde_json::Value".to_string(),
        }
    }

    /// Convert a param type to Rust (params only support primitives and arrays).
    fn param_type_to_rust(&self, ty: &LexUserType) -> String {
        match ty {
            LexUserType::String(_) => "String".to_string(),
            LexUserType::Integer(_) => "i64".to_string(),
            LexUserType::Boolean(_) => "bool".to_string(),
            LexUserType::Array(arr) => {
                let inner = self.param_type_to_rust(&arr.items);
                format!("Vec<{inner}>")
            }
            LexUserType::Unknown(_) => "String".to_string(),
            _ => "String".to_string(),
        }
    }

    /// Convert a ref target to a Rust type path.
    fn ref_to_rust(&self, current_nsid: &str, ref_target: &str) -> String {
        let (ref_nsid, ref_def) = parse_ref(current_nsid, ref_target);

        if ref_nsid == current_nsid {
            // Local reference within the same file
            def_name_to_type(&ref_def)
        } else {
            // Cross-module reference
            let parts: Vec<&str> = ref_nsid.split('.').collect();
            let module_path = parts
                .iter()
                .map(|p| sanitize_ident(p))
                .collect::<Vec<_>>()
                .join("::");
            let type_name = def_name_to_type(&ref_def);
            format!("crate::{module_path}::{type_name}")
        }
    }
}

// --- Naming utilities ---

/// Parse a ref string into (nsid, def_name).
/// Refs can be:
/// - "#defName" -> (current_nsid, defName)
/// - "some.nsid#defName" -> (some.nsid, defName)
/// - "some.nsid" -> (some.nsid, main)
fn parse_ref(current_nsid: &str, ref_str: &str) -> (String, String) {
    if let Some(suffix) = ref_str.strip_prefix('#') {
        (current_nsid.to_string(), suffix.to_string())
    } else if let Some(pos) = ref_str.find('#') {
        (ref_str[..pos].to_string(), ref_str[pos + 1..].to_string())
    } else {
        (ref_str.to_string(), "main".to_string())
    }
}

/// Convert a def name to a Rust type name (PascalCase).
/// Avoids conflicts with standard library types.
fn def_name_to_type(def_name: &str) -> String {
    if def_name == "main" {
        "Main".to_string()
    } else {
        let name = to_pascal_case(def_name);
        sanitize_type_name(&name)
    }
}

/// Ensure a type name doesn't conflict with standard library types.
fn sanitize_type_name(name: &str) -> String {
    match name {
        "Option" => "LexOption".to_string(),
        "Result" => "LexResult".to_string(),
        "Error" => "LexError".to_string(),
        "Box" => "LexBox".to_string(),
        "String" => "LexString".to_string(),
        "Vec" => "LexVec".to_string(),
        _ => name.to_string(),
    }
}

/// Generate a variant name for a union member.
fn ref_to_variant_name(nsid: &str, def_name: &str) -> String {
    // Use the last two parts of the NSID + def for uniqueness
    let parts: Vec<&str> = nsid.split('.').collect();
    let suffix = if def_name == "main" {
        String::new()
    } else {
        to_pascal_case(def_name)
    };

    if parts.len() >= 2 {
        let ns = to_pascal_case(parts[parts.len() - 2]);
        let name = to_pascal_case(parts[parts.len() - 1]);
        format!("{ns}{name}{suffix}")
    } else {
        let name = to_pascal_case(parts.last().unwrap_or(&"Unknown"));
        format!("{name}{suffix}")
    }
}

/// Convert a string to PascalCase.
fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for ch in s.chars() {
        if !ch.is_ascii_alphanumeric() {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(ch.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(ch);
        }
    }

    // Ensure it starts with uppercase
    if let Some(first) = result.chars().next() {
        if first.is_ascii_digit() {
            result = format!("V{result}");
        }
    }

    result
}

/// Convert a string to snake_case.
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    let mut prev_was_upper = false;

    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i > 0 && !prev_was_upper {
                result.push('_');
            }
            result.push(ch.to_ascii_lowercase());
            prev_was_upper = true;
        } else if ch == '-' || ch == '.' || ch == '#' {
            result.push('_');
            prev_was_upper = false;
        } else if !ch.is_ascii_alphanumeric() && ch != '_' {
            // Strip non-alphanumeric chars like '!'
            prev_was_upper = false;
        } else {
            prev_was_upper = false;
            result.push(ch);
        }
    }

    sanitize_ident(&result)
}

/// Convert snake_case back to camelCase for comparison.
fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;

    for ch in s.chars() {
        if ch == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(ch.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(ch);
        }
    }
    result
}

/// Convert a string to SCREAMING_SNAKE_CASE.
fn to_screaming_snake(s: &str) -> String {
    let snake = to_snake_case(s);
    snake.to_ascii_uppercase()
}

/// Sanitize a Rust identifier, escaping keywords.
fn sanitize_ident(s: &str) -> String {
    let s = s.replace('-', "_");
    match s.as_str() {
        "type" | "self" | "super" | "crate" | "mod" | "fn" | "let" | "mut" | "ref" | "match"
        | "if" | "else" | "for" | "while" | "loop" | "break" | "continue" | "return" | "struct"
        | "enum" | "trait" | "impl" | "pub" | "use" | "as" | "in" | "where" | "async" | "await"
        | "move" | "dyn" | "static" | "const" | "extern" | "unsafe" | "true" | "false" => {
            format!("r#{s}")
        }
        _ => s,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("main"), "Main");
        assert_eq!(to_pascal_case("profileView"), "ProfileView");
        assert_eq!(to_pascal_case("feed-view-post"), "FeedViewPost");
        assert_eq!(to_pascal_case("getProfile"), "GetProfile");
    }

    #[test]
    fn test_to_snake_case() {
        assert_eq!(to_snake_case("createdAt"), "created_at");
        assert_eq!(to_snake_case("displayName"), "display_name");
        assert_eq!(to_snake_case("did"), "did");
        assert_eq!(to_snake_case("uri"), "uri");
    }

    #[test]
    fn test_to_camel_case() {
        assert_eq!(to_camel_case("created_at"), "createdAt");
        assert_eq!(to_camel_case("display_name"), "displayName");
    }

    #[test]
    fn test_sanitize_ident() {
        assert_eq!(sanitize_ident("type"), "r#type");
        assert_eq!(sanitize_ident("self"), "r#self");
        assert_eq!(sanitize_ident("normal"), "normal");
        assert_eq!(sanitize_ident("feed-view"), "feed_view");
    }

    #[test]
    fn test_parse_ref() {
        let (nsid, def) = parse_ref("app.bsky.feed.post", "#replyRef");
        assert_eq!(nsid, "app.bsky.feed.post");
        assert_eq!(def, "replyRef");

        let (nsid, def) = parse_ref("app.bsky.feed.post", "app.bsky.actor.defs#profileView");
        assert_eq!(nsid, "app.bsky.actor.defs");
        assert_eq!(def, "profileView");

        let (nsid, def) = parse_ref("app.bsky.feed.post", "app.bsky.embed.images");
        assert_eq!(nsid, "app.bsky.embed.images");
        assert_eq!(def, "main");
    }

    #[test]
    fn test_def_name_to_type() {
        assert_eq!(def_name_to_type("main"), "Main");
        assert_eq!(def_name_to_type("profileView"), "ProfileView");
        assert_eq!(def_name_to_type("feedViewPost"), "FeedViewPost");
    }

    #[test]
    fn test_ref_to_variant_name() {
        assert_eq!(
            ref_to_variant_name("app.bsky.embed.images", "main"),
            "EmbedImages"
        );
        assert_eq!(
            ref_to_variant_name("app.bsky.embed.external", "main"),
            "EmbedExternal"
        );
        assert_eq!(
            ref_to_variant_name("app.bsky.actor.defs", "profileView"),
            "ActorDefsProfileView"
        );
    }

    #[test]
    fn test_to_screaming_snake() {
        assert_eq!(to_screaming_snake("active"), "ACTIVE");
        assert_eq!(to_screaming_snake("takedown"), "TAKEDOWN");
        assert_eq!(to_screaming_snake("content-media"), "CONTENT_MEDIA");
    }
}
